name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          GCP_PLATFORM_DEPLOY_SA: ${{ secrets.GCP_PLATFORM_DEPLOY_SA }}
          GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add GCP_PLATFORM_DEPLOY_SA="$GCP_PLATFORM_DEPLOY_SA" GCP_WIF_PROVIDER="$GCP_WIF_PROVIDER" --repo ditto-assistant/ditto-platform
  variables:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import variables
        env:
          DITTO_DASHBOARD_WANDB_URL: ${{ vars.DITTO_DASHBOARD_WANDB_URL }}
        run: |
          unset DEPOT_TOKEN
          depot ci vars add DITTO_DASHBOARD_WANDB_URL="$DITTO_DASHBOARD_WANDB_URL" --repo ditto-assistant/ditto-platform
